### ISSUE TITLE
Camera Substitute

### ISSUE THREAD

**Issue by paul-g** [ic-cubesat/cubemu#5]
Since we won't have a sensor in time for the Hackathon, I'm looking for an alternative. Probably a phone camera or a web camera should do if we connect them to a laptop.

**Comment by alan-y-han** [comment]
I have a 720p USB webcam I could lend, but in case I cannot make it, it may be a good idea for someone else to also bring one.

**Comment by paul-g** [comment]
Yeah, I have one as well. It seems [pygame](http://pygame.org/news.html) or [OpenCV](https://opencv-python-tutroals.readthedocs.org/en/latest/py_tutorials/py_setup/py_table_of_contents_setup/py_table_of_contents_setup.html) (related [SO Post](http://stackoverflow.com/questions/604749/how-do-i-access-my-webcam-in-python) could be used for this. I ll give this a go.
